### ISSUE TITLE
ユーザキーワード未登録時「@MentorPocket\n暇」と投稿すると「暇」がセットされる

### ISSUE THREAD

**Issue by eggplants** [enpitut2020/PocketMentor#1]
はじめまして。
@Hotsukai さんに「issue立てて」と言われたので立てます。
今、Userが暇な時のキーワード未登録の時「@MentorPocket\n暇」と投稿すると、「暇」がキーワードとして登録されてしまいます。
許容される挙動であればwontfixとしてください。

例:
https://twitter.com/MentorPocket/status/1288295625977548801

**Comment by hotsukai** [comment]
ありがとうございます。
`@MentorPocket 夏季休暇なにかしたい`
のようなツイートの場合、キーワード登録はして、リマインド+記事推薦はしない必要がありますので、
`@MentorPocket\n暇` がキーワードとして登録されるのは仕様です。
しかしこのツイートに対してリマインド+記事推薦をしてしまうのは修正する必要があります。
チームに余裕ができ次第、順次対応予定です。
