### ISSUE TITLE
全角の「＠」が除去されない

### ISSUE THREAD

**Issue by eggplants** [enpitut2020/PocketMentor#2]
Twitterはメンションに全角/半角両方の`@`が使用可能ですが、正規表現で半角しか除去されていないところがあります。
これにより「＠MentorPocket」を含むキーワードやスクリーンネームを使われると意図しない挙動になりそうです。
@Hotsukai さんがサイレント修正済みとのことですが一応立てておきます。

**Comment by hotsukai** [comment]
報告ありがとうございます。
1bde0f1698e3d7de2b8deba5f93e222d1e4183a3 にて修正しました。
